name: package-getting-started-app
on:
  push:
    branches:
      - main

jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check the Code
        run: |
          npm install
          npm run lint
          npm test
          echo "Code verification complete."

      - name: Build and Tag Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest myrepo/myapp:latest
          echo "Image built and tagged."

      - name: Push Image to Docker Hub
        run: |
          docker login -u damien.vigouroux@viacesi.fr -p qo2Z#%2d8#VKgkEf
          docker push myrepo/myapp:latest
          echo "Image pushed to Docker Hub."

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          echo "Application deployed to Kubernetes."

      - name: Run Integration Tests
        run: |
          # Run integration tests against deployed application
          echo "Running integration tests..."
